# Lab Exercises--Strictly NumPy

In [1]:
import numpy as np
import doctest

## Exercise 1
Implement the following function so that it performs element-wise addition using numpy operations:

<a href="https://www.w3schools.com/python/numpy/numpy_ufunc_simple_arithmetic.asp">Click here to visit some useful references.</a>

In [2]:
def add_arrays_numpy(arr_1, arr_2):
    """
    Example doctests given below:
    
    >>> result_array = add_arrays_numpy(np.array([1, 2, 3]), np.array([2, 3, 4]))
    >>> assert isinstance(result_array, np.ndarray)
    >>> assert len(result_array) == 3
    >>> result_array
    array([3, 5, 7])
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests. If no error messages are revealed, then you've passed all tests!

In [3]:
doctest.run_docstring_examples(add_arrays_numpy, globals())

**********************************************************************
File "__main__", line 6, in NoName
Failed example:
    assert isinstance(result_array, np.ndarray)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[1]>", line 1, in <module>
        assert isinstance(result_array, np.ndarray)
    AssertionError
**********************************************************************
File "__main__", line 7, in NoName
Failed example:
    assert len(result_array) == 3
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[2]>", line 1, in <module>
        assert len(result_array) == 3
    TypeErr

## Exercise 2
Implement the following function so that it takes the mean along the rows of a given matrix using numpy operations.

<a href="https://numpy.org/doc/stable/reference/generated/numpy.mean.html">Click here to visit useful references.</a>

In [4]:
def find_mean_matrix_row_numpy(matrix):
    """
    >>> result_1 = find_mean_matrix_row_numpy(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
    >>> assert np.all(np.isclose(np.array([2., 5., 8.]), result_1))
    >>> result_2 = find_mean_matrix_row_numpy(np.array([[-1, 100, 3], [5, 6, 10], [-3, 6, -9]]))
    >>> assert np.all(np.isclose(np.array([34., 7., -2.]), result_2))
    >>> result_3 = find_mean_matrix_row_numpy(np.array([[0, 0], [1, 0], [0, 1]]))
    >>> assert np.all(np.isclose(np.array([0, 0.5, 0.5]), result_3))
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests.

In [5]:
doctest.run_docstring_examples(find_mean_matrix_row_numpy, globals())

**********************************************************************
File "__main__", line 4, in NoName
Failed example:
    assert np.all(np.isclose(np.array([2., 5., 8.]), result_1))
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[1]>", line 1, in <module>
        assert np.all(np.isclose(np.array([2., 5., 8.]), result_1))
      File "<__array_function__ internals>", line 5, in isclose
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/numeric.py", line 2356, in isclose
        yfin = isfinite(y)
    TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
**********************************************************************

## Exercise 3
Implement the following function so that it takes the sum along the rows of a given matrix strictly using numpy operations.

<a href="https://numpy.org/doc/stable/reference/generated/numpy.sum.html">Click here for hints and references</a>

In [6]:
def sum_matrix_row_numpy(matrix):
    """
    >>> result = sum_matrix_row_numpy(np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]]))
    >>> assert result.shape == (3,)
    >>> assert isinstance(result, np.ndarray)
    >>> result
    array([3, 6, 9])
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests.

In [7]:
doctest.run_docstring_examples(sum_matrix_row_numpy, globals())

**********************************************************************
File "__main__", line 4, in NoName
Failed example:
    assert result.shape == (3,)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[1]>", line 1, in <module>
        assert result.shape == (3,)
    AttributeError: 'NoneType' object has no attribute 'shape'
**********************************************************************
File "__main__", line 5, in NoName
Failed example:
    assert isinstance(result, np.ndarray)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[2]>", line 1, in <module>
        assert isinstance(res

## Exercise 4
Implement the following function so that it takes the sum along the columns of a given matrix strictly using numpy operations.

<a href="https://numpy.org/doc/stable/reference/generated/numpy.sum.html">Click here if you are stuck.</a>

In [8]:
def sum_matrix_column_numpy(matrix):
    """
    >>> result = sum_matrix_column_numpy([[-3, -2, 100], [333, 333, 333], [0.5, -1.6, -100]])
    >>> assert isinstance(result, np.ndarray)
    >>> assert np.all(np.isclose(np.array([330.5, 329.4, 333]), result))
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests.

In [9]:
doctest.run_docstring_examples(sum_matrix_column_numpy, globals())

**********************************************************************
File "__main__", line 4, in NoName
Failed example:
    assert isinstance(result, np.ndarray)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[1]>", line 1, in <module>
        assert isinstance(result, np.ndarray)
    AssertionError
**********************************************************************
File "__main__", line 5, in NoName
Failed example:
    assert np.all(np.isclose(np.array([330.5, 329.4, 333]), result))
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[2]>", line 1, in <module>
        assert np.all(np.i

## Exercise 5
Implement the following function so that it finds the index of the minimum value in a given array only using numpy operation.

<a href="https://www.geeksforgeeks.org/numpy-argmin-python/">Click for help</a>

In [10]:
def find_min_index_numpy(arr):
    """
    >>> find_min_index_numpy([1,2,3,4])
    0
    >>> find_min_index_numpy([0,0,0])
    0
    >>> find_min_index_numpy([3,2,1,0])
    3
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests.

In [11]:
doctest.run_docstring_examples(find_min_index_numpy, globals())

**********************************************************************
File "__main__", line 3, in NoName
Failed example:
    find_min_index_numpy([1,2,3,4])
Expected:
    0
Got nothing
**********************************************************************
File "__main__", line 5, in NoName
Failed example:
    find_min_index_numpy([0,0,0])
Expected:
    0
Got nothing
**********************************************************************
File "__main__", line 7, in NoName
Failed example:
    find_min_index_numpy([3,2,1,0])
Expected:
    3
Got nothing


## Exercise 6
Implement the following function so that it finds the index of the minimum value in a given matrix along each row only using numpy operation.

<a href="https://www.geeksforgeeks.org/numpy-argmin-python/">Try something out yourself before clicking</a>

In [12]:
def find_min_matrix_numpy(matrix):
    """
    >>> index_array = find_min_matrix_numpy([[3, 2, 1], [-1000, 0, 0], [1.1, 1.01, 1.001], [1, 0.999, 0.998]])
    >>> assert len(index_array) == 4
    >>> assert isinstance(index_array, np.ndarray)
    >>> index_array
    array([2, 0, 2, 2])
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests.

In [13]:
doctest.run_docstring_examples(find_min_matrix_numpy, globals())

**********************************************************************
File "__main__", line 4, in NoName
Failed example:
    assert len(index_array) == 4
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[1]>", line 1, in <module>
        assert len(index_array) == 4
    TypeError: object of type 'NoneType' has no len()
**********************************************************************
File "__main__", line 5, in NoName
Failed example:
    assert isinstance(index_array, np.ndarray)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[2]>", line 1, in <module>
        assert isinstance(index

## Exercise 7
Implement the following function so that it calculates the squared distance between point a and point b strictly using numpy operations.

In [14]:
def calc_sq_distance_numpy(point_a, point_b):
    """
    >>> calc_sq_distance_numpy((0,0), (3,4))
    25
    >>> calc_sq_distance_numpy((0,0), (0,0))
    0
    >>> calc_sq_distance_numpy((0,0), (100,1))
    10001
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests.

In [15]:
doctest.run_docstring_examples(calc_sq_distance_numpy, globals())

**********************************************************************
File "__main__", line 3, in NoName
Failed example:
    calc_sq_distance_numpy((0,0), (3,4))
Expected:
    25
Got nothing
**********************************************************************
File "__main__", line 5, in NoName
Failed example:
    calc_sq_distance_numpy((0,0), (0,0))
Expected:
    0
Got nothing
**********************************************************************
File "__main__", line 7, in NoName
Failed example:
    calc_sq_distance_numpy((0,0), (100,1))
Expected:
    10001
Got nothing


## Exercise 8
Implement the following function so that given an array, it returns a separate matrix where it assigns its minimum value to 1 while all others to 0.

If you got stuck, maybe revert back to trying out your good old friend "for-loop". Try if you can get things done with him first.

In [16]:
def assign_rank_numpy(matrix):
    """
    >>> rank_matrix = assign_rank_numpy([[3, 2, 1], [-1000, 0, 0], [1.1, 1.01, 1.001], [1, 0.999, 0.998]])
    >>> assert isinstance(rank_matrix, np.ndarray)
    >>> rank_matrix.shape
    (4, 3)
    >>> rank_matrix
    array([[0., 0., 1.],
           [1., 0., 0.],
           [0., 0., 1.],
           [0., 0., 1.]])
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests.

In [17]:
doctest.run_docstring_examples(assign_rank_numpy, globals())

**********************************************************************
File "__main__", line 4, in NoName
Failed example:
    assert isinstance(rank_matrix, np.ndarray)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[1]>", line 1, in <module>
        assert isinstance(rank_matrix, np.ndarray)
    AssertionError
**********************************************************************
File "__main__", line 5, in NoName
Failed example:
    rank_matrix.shape
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[2]>", line 1, in <module>
        rank_matrix.shape
    AttributeError: 'NoneType' object

## Exercise 9
Implement the following function so that it builds an identity matrix with the specified dimension strictly using numpy operations.

<a href="https://en.wikipedia.org/wiki/Identity_matrix">What is an identity matrix?---->Wiki Portal</a><br>
<a href="https://www.geeksforgeeks.org/numpy-identity-python/">Stuck? I got you</a>

In [18]:
def build_identity_numpy(dim):
    """
    >>> build_identity_numpy(1)
    array([[1.]])
    >>> build_identity_numpy(0)
    array([], shape=(0, 0), dtype=float64)
    >>> build_identity_numpy(3)
    array([[1., 0., 0.],
           [0., 1., 0.],
           [0., 0., 1.]])
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests.

In [19]:
doctest.run_docstring_examples(build_identity_numpy, globals())

**********************************************************************
File "__main__", line 3, in NoName
Failed example:
    build_identity_numpy(1)
Expected:
    array([[1.]])
Got nothing
**********************************************************************
File "__main__", line 5, in NoName
Failed example:
    build_identity_numpy(0)
Expected:
    array([], shape=(0, 0), dtype=float64)
Got nothing
**********************************************************************
File "__main__", line 7, in NoName
Failed example:
    build_identity_numpy(3)
Expected:
    array([[1., 0., 0.],
           [0., 1., 0.],
           [0., 0., 1.]])
Got nothing


## Exercise 10
Implement the following function so that it defines a matrix of 1's with the specified dimensions strictly using numpy operations.

<a href="https://www.w3resource.com/numpy/array-creation/ones.php">Help Center</a>

In [20]:
def build_matrix_numpy(num_row, num_column):
    """
    >>> build_matrix_numpy(4, 3)
    array([[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]])
    >>> build_matrix_numpy(10, 3)
    array([[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]])
    >>> build_matrix_numpy(1, 0) # shouldn't be able to create a matrix where row or column is passed in as 0
    array([], shape=(1, 0), dtype=float64)
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests.

In [21]:
doctest.run_docstring_examples(build_matrix_numpy, globals())

**********************************************************************
File "__main__", line 3, in NoName
Failed example:
    build_matrix_numpy(4, 3)
Expected:
    array([[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]])
Got nothing
**********************************************************************
File "__main__", line 8, in NoName
Failed example:
    build_matrix_numpy(10, 3)
Expected:
    array([[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]])
Got nothing
**********************************************************************
File "__main__", line 19, in NoName
Failed example:
    build_matrix_numpy(1, 0) # shouldn't be able to create a matrix where row or column is passed in as 0
Expected:
    array([], shape=(1, 0), dtype=float64)
Got nothing


## Exercise 11
Implement the following function so that it defines a matrix of 0's with the specified dimensions strictly using numpy operations.

<a href="https://www.geeksforgeeks.org/numpy-zeros-python/">Teleport you to somewhere with hints.</a>

In [22]:
def build_matrix_0_numpy(num_row, num_column):
    """
    >>> build_matrix_0_numpy(2, 3)
    array([[0., 0., 0.],
           [0., 0., 0.]])
    >>> build_matrix_0_numpy(6, 3)
    array([[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]])
    >>> build_matrix_0_numpy(0, 1) # shouldn't be able to create a matrix where row or column is passed in as 0
    array([], shape=(0, 1), dtype=float64)
    """

When you have finished implementation, run the cell below to see if your code passes all example doctests.

In [23]:
doctest.run_docstring_examples(build_matrix_0_numpy, globals())

**********************************************************************
File "__main__", line 3, in NoName
Failed example:
    build_matrix_0_numpy(2, 3)
Expected:
    array([[0., 0., 0.],
           [0., 0., 0.]])
Got nothing
**********************************************************************
File "__main__", line 6, in NoName
Failed example:
    build_matrix_0_numpy(6, 3)
Expected:
    array([[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]])
Got nothing
**********************************************************************
File "__main__", line 13, in NoName
Failed example:
    build_matrix_0_numpy(0, 1) # shouldn't be able to create a matrix where row or column is passed in as 0
Expected:
    array([], shape=(0, 1), dtype=float64)
Got nothing


# End Here
> You've completed all exercises!

Now, run the cell below to comprehensively check for one last time if all doctest cases are passed.

In [24]:
doctest.testmod()

**********************************************************************
File "__main__", line 6, in __main__.add_arrays_numpy
Failed example:
    assert isinstance(result_array, np.ndarray)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest __main__.add_arrays_numpy[1]>", line 1, in <module>
        assert isinstance(result_array, np.ndarray)
    AssertionError
**********************************************************************
File "__main__", line 7, in __main__.add_arrays_numpy
Failed example:
    assert len(result_array) == 3
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest __main__.add_arrays_numpy

TestResults(failed=32, attempted=40)